# Generated by Django 2.1.3 on 2018-11-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computername', models.CharField(max_length=200)),
                ('biosserial', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('osname', models.CharField(max_length=200)),
                ('osversion', models.CharField(max_length=200)),
                ('spversion', models.CharField(max_length=200)),
                ('totalram', models.CharField(max_length=200)),
                ('processors', models.CharField(max_length=100)),
                ('lprocessors', models.CharField(max_length=200)),
            ],
        ),
    ]
