# Generated by Django 2.1.3 on 2018-11-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='biosserial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='lprocessors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='osname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='osversion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='processors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='spversion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='totalram',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
